DELETE MOVIE_ACTOR FROM MOVIE_ACTOR
JOIN ACTOR USING (ActorId)
JOIN MOVIE_GENRE USING (MovieId)
JOIN GENRE ON (MOVIE_GENRE.GenreId = GENRE.GenreId)
WHERE ACTOR.Name = 'Tom Cruise' AND GENRE.Label = 'Action';