SELECT STREAM.StreamDate, MOVIE.Title, CUSTOMER.Name, CUSTOMER.Country
FROM STREAM
NATURAL JOIN MOVIE
NATURAL JOIN CUSTOMER
WHERE 
MovieId IN(
    SELECT MovieId
    FROM MOVIE_ACTOR
    NATURAL JOIN ACTOR
    WHERE ACTOR.Name = 'Johnny Depp'
)
AND
MovieId NOT IN(
    SELECT MovieId
    FROM MOVIE_ACTOR
    NATURAL JOIN ACTOR
    WHERE ACTOR.Name = 'Helena Bonham Carter'
)
AND
CustomerId NOT IN(
    SELECT CustomerId
    FROM CUSTOMER
    JOIN COUNTRY ON (CUSTOMER.Country = COUNTRY.Name)
    WHERE COUNTRY.Name = 'China'
)
ORDER BY STREAM.StreamDate DESC
LIMIT 15;