SELECT GENRE.Label, REGION.Name, COUNT(STREAM.StreamDate)
FROM (GENRE,REGION) LEFT OUTER JOIN (MOVIE_GENRE NATURAL JOIN MOVIE NATURAL JOIN STREAM NATURAL JOIN CUSTOMER JOIN COUNTRY)
ON (GENRE.GenreId = MOVIE_GENRE.GenreId AND COUNTRY.RegionId = REGION.RegionId AND CUSTOMER.Country = COUNTRY.Name)
GROUP BY GENRE.Label, REGION.Name
ORDER BY GENRE.Label ASC, REGION.Name ASC;