SELECT CUSTOMER.Name, MAX(STREAM.Charge)
FROM CUSTOMER, STREAM
WHERE CUSTOMER.Country = 'United States' AND CUSTOMER.CustomerId = STREAM.CustomerId AND STREAM.StreamDate LIKE '2018%'
GROUP BY CUSTOMER.Name
ORDER BY MAX(STREAM.Charge) DESC, CUSTOMER.Name ASC;