SELECT MOVIE.Title, COUNT(STREAM.StreamDate) AS N 
FROM MOVIE
NATURAL JOIN STREAM
NATURAL JOIN CUSTOMER
JOIN COUNTRY ON (CUSTOMER.Country = COUNTRY.Name)
JOIN REGION USING (RegionId)
WHERE REGION.Name = 'Asia'
GROUP BY Title
ORDER BY N DESC, Title ASC
LIMIT 20;