SELECT DISTINCT Title
FROM MOVIE
JOIN MOVIE_GENRE ON(MOVIE.MovieId = MOVIE_GENRE.MovieId)
JOIN GENRE ON(MOVIE_GENRE.GenreId = GENRE.GenreId)
WHERE 
MOVIE.MovieId IN 
    (SELECT MovieId
    FROM MOVIE_GENRE
    JOIN GENRE ON(MOVIE_GENRE.GenreId = GENRE.GenreId)
    WHERE Label='Action'
)
AND 
MOVIE.MovieId IN 
    (SELECT MovieId
    FROM MOVIE_GENRE
    JOIN GENRE ON(MOVIE_GENRE.GenreId = GENRE.GenreId)
    WHERE Label='Comedy'
)
ORDER BY Title ASC;